services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=uit2024
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true

volumes:
  es-data:
    driver: local
